### ISSUE TITLE
how to do setup?

### ISSUE THREAD

**Issue by ddmakadia1699** [trevorhobenshield/amazon_photos#11]
facing issue while finding cookies

Log in to Amazon Photos and copy the following cookies:

![image](https://github.com/trevorhobenshield/amazon_photos/assets/38184843/6a897ed5-ac0d-4008-9cf8-ddd9c8cfceb4)

**Comment by lambertlu** [comment]
I have same issue.

```
from amazon_photos import AmazonPhotos

ap = AmazonPhotos(
    cookies={
        'ubid_main':'131-9...5-2...61',
        'at_main':'Atza|IwEBIFqEThTFm2n6xKz.....hQiHhuHGDZm23n7kw',
        'session-id':'133-0...1-5...0',
    },
    # optionally cache all intermediate JSON responses
    tmp='tmp',
    # pandas options
    dtype_backend='pyarrow',
    engine='pyarrow',
)

# get current usage stats
ap.usage()


```

The error message:

`$ python3 ap.py
2024-02-17 11:35:06.024 [ERROR] :: 401 {"Message":"No Auth Method Provided"}
2024-02-17 11:35:06.025 [ERROR] :: Cookies expired. Log in to Amazon Photos and copy fresh cookies.
2024-02-17 11:35:06.885 [ERROR] :: 401 {"Message":"No Auth Method Provided"}
2024-02-17 11:35:06.885 [ERROR] :: Cookies expired. Log in to Amazon Photos and copy fresh cookies.
2024-02-17 11:35:07.896 [ERROR] :: 401 {"Message":"No Auth Method Provided"}
2024-02-17 11:35:07.896 [ERROR] :: Cookies expired. Log in to Amazon Photos and copy fresh cookies.
2024-02-17 11:35:08.785 [ERROR] :: 401 {"Message":"No Auth Method Provided"}
2024-02-17 11:35:08.785 [ERROR] :: Cookies expired. Log in to Amazon Photos and copy fresh cookies.
2024-02-17 11:35:15.771 [ERROR] :: 401 {"Message":"No Auth Method Provided"}
2024-02-17 11:35:15.772 [ERROR] :: Cookies expired. Log in to Amazon Photos and copy fresh cookies.
2024-02-17 11:35:31.421 [ERROR] :: 401 {"Message":"No Auth Method Provided"}
2024-02-17 11:35:31.422 [ERROR] :: Cookies expired. Log in to Amazon Photos and copy fresh cookies.
2024-02-17 11:35:40.224 [ERROR] :: 401 {"Message":"No Auth Method Provided"}
2024-02-17 11:35:40.224 [ERROR] :: Cookies expired. Log in to Amazon Photos and copy fresh cookies.
2024-02-17 11:36:00.340 [ERROR] :: 401 {"Message":"No Auth Method Provided"}
2024-02-17 11:36:00.340 [ERROR] :: Cookies expired. Log in to Amazon Photos and copy fresh cookies.
2024-02-17 11:36:01.292 [ERROR] :: 401 {"Message":"No Auth Method Provided"}
2024-02-17 11:36:01.292 [ERROR] :: Cookies expired. Log in to Amazon Photos and copy fresh cookies.
2024-02-17 11:36:21.438 [ERROR] :: 401 {"Message":"No Auth Method Provided"}
2024-02-17 11:36:21.438 [ERROR] :: Cookies expired. Log in to Amazon Photos and copy fresh cookies.
2024-02-17 11:36:41.615 [ERROR] :: 401 {"Message":"No Auth Method Provided"}
2024-02-17 11:36:41.615 [ERROR] :: Cookies expired. Log in to Amazon Photos and copy fresh cookies.
2024-02-17 11:37:01.826 [ERROR] :: 401 {"Message":"No Auth Method Provided"}
2024-02-17 11:37:01.826 [ERROR] :: Cookies expired. Log in to Amazon Photos and copy fresh cookies.
2024-02-17 11:37:21.961 [ERROR] :: 401 {"Message":"No Auth Method Provided"}
2024-02-17 11:37:21.961 [ERROR] :: Cookies expired. Log in to Amazon Photos and copy fresh cookies.
Traceback (most recent call last):
  File "/home/lambert/amazon_photos/ap.py", line 3, in <module>
    ap = AmazonPhotos(
  File "/home/lambert/.local/lib/python3.10/site-packages/amazon_photos/_api.py", line 77, in __init__
    self.root = self.get_root()
  File "/home/lambert/.local/lib/python3.10/site-packages/amazon_photos/_api.py", line 925, in get_root
    root = r.json()['data'][0]
AttributeError: 'NoneType' object has no attribute 'json'`

**Comment by rarents1975** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
denis-mirchandani, @johan-t, @MK2112, @adarshxs, @Ritesh1137, @ActurialCapital, @kentotomita, @sryio, @constantinrusu, @spica314, @freemty, @cgatno, @ahaymro, @numago, @iibrahimli, @leodambrosi, @sekasx, @RichardScottOZ, @gansongyuan, @d3nnyyy

**Comment by lambertlu** [comment]
> Hello,
> 
> We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!
> 
> As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:
> 
> * Health insurance coverage
> * Retirement savings plan
> * Flexible work schedule
> * Generous vacation and paid time off
> * Professional development opportunities
> 
> To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.
> 
> Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.
> 
> **Important:** You have 24 hours to complete the application process.
> 
> If you have any questions or need further information, please don't hesitate to contact us.
> 
> Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.
> 
> Best regards, GitHub Recruitment Team denis-mirchandani, @johan-t, @MK2112, @adarshxs, @Ritesh1137, @ActurialCapital, @kentotomita, @sryio, @constantinrusu, @spica314, @freemty, @cgatno, @ahaymro, @numago, @iibrahimli, @leodambrosi, @sekasx, @RichardScottOZ, @gansongyuan, @d3nnyyy

Report this fraud.

**Comment by rarents1975** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
tingez, @alexsniffin, @panda1942-ai, @isaacperez, @mark-antal-csizmadia, @charlieWyatt, @ubermenchh, @svilupp, @LeiHHHuang, @sumsuddin, @hexhew, @madroidmaq, @limitty, @MattYoon, @yfme, @MohammedMahmoud01, @pcbill, @ethanbleier, @ahpuchend, @dlwslb
